const mongoose = require('mongoose');

const jobSchema = new mongoose.Schema({
  recruiterId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  title: { type: String, required: true },
  company: { type: String, required: true },
  description: { type: String, required: true },
  requirements: [{ type: String }],
  location: { type: String },
  salaryRange: { type: String },
  experience: { type: String }, // e.g., '0-2 years', '3-5 years'
  noticePeriod: { type: String }, // e.g., 'Immediate', '30 Days'
  status: { type: String, enum: ['active', 'closed'], default: 'active' },
  
  // Vector representation of Job Description generated by AI Service
  embeddedJD: { type: [Number] }
}, { timestamps: true });

module.exports = mongoose.model('Job', jobSchema);
